name: Pytest Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # container:
    #   image: docker://josephhilby/lunch_and_learn_docker:latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: josephhilby/lunch_and_learn_docker:latest
      -
        name: Run Tests
        run: |
          pytest -s
